### PR TITLE
dumpstats modification to go with nciaccountapi branch in ncigrafana

### PR DESCRIPTION
**Pull request by dsroberts**
Modification to dumpstats to use the updated parse_user_storage_data in ncigrafana/nciaccountapi branch. Removes dump_storage step and runs upload_storage once per mount instead of once per project per mount.

### CODE REVIEW

**Comment by aidanheerdegen** [comment]
Not parsing human-readable output is a big improvement. 

There is some value in still dumping the output to a physical file (in JSON format I guess)
- Can help diagnose issues with the data in the DB. If dumps are ok, means something failed with DB update.
- Backup if DB update fails. Upload can be re-run when infra is fixed.

The second function could be accomplished by dumping output if DB update fails.

There is a downside to dumping all that data: you now have a lot of data files. That could be addressed by only keeping x days worth and doing some sort of logrotate?

Feel free to ignore above, just wanted to give that perspective of having to diagnose when things "Went wrong". Granted that was probably due to parsing errors when formatting of tools changed, or some funkiness with the ssh tunnel, neither of which will be issues.

**Comment by dsroberts** [comment]
Yep, that's a good idea. Right now it seems everything since the start of this year is being kept, and all of 2019 is in a single tar file. Some automated handling of log rotation would be good. Something like that can be added as the final task of the doit task list.

**Comment by aidanheerdegen** [comment]
Yeah I just archived it all, bit of a magpie and a "why not" in case there was something in there that we subsequently wanted. Really should have reassessed if that was really necessary. It is good to have 7-10 day buffer, because there isn't much in the way of error checking, so it only really surfaces when someone notices b0rked plots.

Speaking of which, I did mean to add something to check the tools were working correctly. One thing that happened a few times was the crawling tools would fall over, and so the report tools which just keep regurgitating the same data (and date stamp). Again I would only detect it when the plots looked flat.

**Comment by dsroberts** [comment]
OK, cool, I'll add your suggestions as issues, that way I won't forget about them.

**Pull request merged**
